### ISSUE TITLE
Update ipynb files

### ISSUE THREAD

**Issue by chrisgilmerproj** [skyfielders/astronomy-notebooks#18]
@erinspace @chrisgilmerproj
- [x] `Asteroids.ipynb`  
- [x] `Axis-Wobble.ipynb`
- [x] `Hertzsprung-Russell.ipynb`
- [ ] `Interactive-3D-Earth-Satellites.ipynb`
- [ ] `Interactive-3D-Solar-System.ipynb`
- [ ] `Interactive-Sky.ipynb`
- [x] `Javascript-integration.ipynb`
- [x] `Stars.ipynb`
- [x] `Stellar-Color-Index.ipynb`
- [x] `Utils-HORIZONS-data.ipynb`

**Comment by erinspace** [comment]
Working on Asteroids.ipnb!

**Comment by chrisgilmerproj** [comment]
Working on `Hertzsprung-Russell.ipynb`

**Comment by chrisgilmerproj** [comment]
Working on `Axis-Wobble.ipynb`

**Comment by erinspace** [comment]
working on ```Interactive-3D-Earth-Satellites.ipynb```

**Comment by chrisgilmerproj** [comment]
Working on `Interactive-3D-Solar-System.ipynb`

**Comment by chrisgilmerproj** [comment]
Working on `Stars.ipynb` because I'm stuck on `Interactive-3D-Solar-System.ipynb`

**Comment by erinspace** [comment]
Moving on to ```Stellar-Color-Index.ipynb``` because I also got stuck on ```Interactive-3D-Earth-Satellites.ipynb``` with the error: 

This program needs access to the screen.
Please run with a Framework build of python, and only when you are
logged in on the main display of your Mac.

**Comment by chrisgilmerproj** [comment]
Working on `Javascript-integration.ipynb`

**Comment by chrisgilmerproj** [comment]
The interactive books I believe need this addition to them:

```python
import os
os.environ['ETS_TOOLKIT'] = 'qt4'
```

This advice was grabbed from the example at: http://docs.enthought.com/mayavi/mayavi/auto/example_qt_embedding.html

**Comment by chrisgilmerproj** [comment]
This is old enough its probably worth closing.
