### ISSUE TITLE
License information for repo

### ISSUE THREAD

**Issue by eleanorlutz** [skyfielders/astronomy-notebooks#32]
These Jupyter notebooks are awesome! I'd love to use them to learn more about astronomy plotting in Python. Do you have a license (MIT, GNU etc) for people who'd like to use / reference your code?

**Comment by brandon-rhodes** [comment]
Great question! I've just added a LICENSE file — thanks for the prod to get one created!

**Comment by eleanorlutz** [comment]
Thank you so much!
