### ISSUE TITLE
setup.bat probably needs to be updated.

### ISSUE THREAD

**Issue by james-prior** [skyfielders/astronomy-notebooks#7]
setup.bat probably needs to be updated considering how much setup.sh was changed in https://github.com/james-prior/astronomy-notebooks/tree/jep-dev.

**Comment by brandon-rhodes** [comment]
I am planning to deprecate `setup.bat` in favor of something like a Docker image that would let folks play with the notebooks without needing to get their own host operating system into some special state first.
